from django.urls import path
from . import views
from .views import (ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView)



urlpatterns = [
    path('', views.index, name='index'),
    path('about-us/', views.about, name='about-us'),
    path('add/', ProductCreateView.as_view(), name='add_product'),
    path('blog-2-column/', views.blog2column, name='blog-2-column'),
    path('blog-3-column/', views.blog3column, name='blog-3-column'),
    path('blog-audio-format/', views.blogaudioformat, name='blog-audio-format'),
    path('blog-details-left-sidebar/', views.blogdetailsleftsidebar, name='blog-details-left-sidebar'),
    path('blog-details-right-sidebar/', views.blogdetailsrightsidebar, name='blog-details-right-sidebar'),
    path('blog-details/', views.blogdetails, name='blog-details'),
    path('blog-gallery-format/', views.bloggalleryformat, name='blog-gallery-format'),
    path('blog-left-sidebar/', views.blogleftsidebar, name='blog-left-sidebar'),
    path('blog-list-left-sidebar/', views.bloglistleftsidebar, name='blog-list-left-sidebar'),
    path('blog-list-right-sidebar/', views.bloglistrightsidebar, name='blog-list-right-sidebar'),
    path('blog-list/', views.bloglist, name='blog-list'),
    path('blog-right-sidebar/', views.blogrightsidebar, name='blog-right-sidebar'),
    path('blog-video-format/', views.blogvideoformat, name='blog-video-format'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('compare/', views.compare, name='compare'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('index-2/', views.index2, name='index-2'),
    path('index-3/', views.index3, name='index-3'),
    path('index-4/', views.index4, name='index-4'), 
    path('login-register/', views.loginregister, name='login-register'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/product_details/', ProductDetailView.as_view(), name='product_details'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('shop-3-column/', views.shop3column, name='shop-3-column'),
    path('shop-4-column/', views.shop4column, name='shop-4-column'),
    path('shop-left-sidebar/', views.shopleftsidebar, name='shop-left-sidebar'),
    path('shop-list-left-sidebar/', views.shoplistleftsidebar, name='shop-list-left-sidebar'),
    path('shop-list-right-sidebar/', views.shoplistrightsidebar, name='shop-list-right-sidebar'),
    path('shop-list/', views.shoplist, name='shop-list'),
    path('shop-right-sidebar', views.shoprightsidebar, name='shop-right-sidebar'),
    path('shopping-cart/', views.shoppingcart, name='shopping-cart'),
    path('single-product-affiliate/', views.singleproductaffiliate, name='single-product-affiliate'),
    path('single-product-carousel/', views.singleproductcarousel, name='single-product-carousel'),
    path('single-product-gallery-left/', views.singleproductgalleryleft, name='single-product-gallery-left'),
    path('single-product-gallery-right/', views.singleproductgalleryright, name='single-product-gallery-right'),
    path('single-product-group/', views.singleproductgroup, name='single-product-group'),
    path('single-product-normal/', views.singleproductnormal, name='single-product-normal'),
    path('single-product-sale/', views.singleproductsale, name='single-product-sale'),
    path('single-product-tab-style-top/', views.singleproducttabstyletop, name='single-product-tab-style-top'),
    path('single-product-tab-style-left/', views.singleproducttabstyleleft, name='single-product-tab-style-left'),
    path('single-product-tab-style-right/', views.singleproducttabstyleright, name='single-product-tab-style-right'),
    path('single-product/', views.singleproduct, name='single-product'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    
]

